# Generated by Django 2.1.4 on 2019-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_log', '0002_vehiclelog_operator_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelog',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='item_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
