# Generated by Django 2.1.4 on 2019-07-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_log', '0003_auto_20190728_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='vehicle_ref',
            field=models.IntegerField(max_length=20),
        ),
    ]
