# Generated by Django 2.1.4 on 2019-07-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutedata', '0001_initial'),
        ('vehicle_log', '0004_auto_20190729_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutedata.Line'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='vehicle_ref',
            field=models.IntegerField(),
        ),
    ]
