# Generated by Django 2.1.4 on 2019-07-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_log', '0005_auto_20190729_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='rutedata.Line'),
        ),
    ]
