# Generated by Django 3.1.5 on 2021-05-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0012_vehicle_null_fields'),
        ('rutedata', '0002_passingtime_line'),
        ('vehicle_log', '0006_auto_20190729_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_logs', to='rutedata.quay'),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle_type.operator'),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_logs', to='rutedata.quay'),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle_type.vehicle'),
        ),
    ]
