# Generated by Django 3.1.5 on 2021-05-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_log', '0007_log_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclelog',
            options={'ordering': ['-origin_departure_time']},
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='vehicle_ref',
            field=models.IntegerField(db_index=True),
        ),
    ]
