# Generated by Django 3.2.5 on 2021-07-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0013_operator_fields'),
        ('vehicle_log', '0008_index_and_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='vehicle_type.operator'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='origin_departure_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='vehicle_type.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehiclelog',
            index=models.Index(fields=['vehicle_ref', 'origin_departure_time'], name='vehicle_log_vehicle_9a9d81_idx'),
        ),
    ]
