language: python
python:
  - "3.7"
  - "3.8"

cache: pip

before_install:
  - python -m pip install --upgrade pip

script:
  - pip install -r requirements.txt
  - cd vehicle_info
  - cp vehicle_info/local_settings_test.py vehicle_info/local_settings.py
  - python manage.py migrate
