language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip

before_install:
  - python -m pip install --upgrade pip

script:
  - cd vehicle_info
  - cp vehicle_info/local_settings_test.py vehicle_info/local_settings.py
  - python manage.py migrate
