# Generated by Django 2.1.4 on 2019-07-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expected_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=5, verbose_name='Linje materiellet brukes på')),
            ],
            options={
                'ordering': ['line'],
            },
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numlow', models.IntegerField(verbose_name='Internnummer fra')),
                ('numhigh', models.IntegerField(verbose_name='Internnummer til')),
                ('type', models.CharField(blank=True, default='', max_length=200, verbose_name='Type/modell')),
                ('length', models.IntegerField(blank=True, default=0, verbose_name='Lengde')),
                ('year', models.IntegerField(blank=True, default=0, verbose_name='Årsmodell')),
                ('fuel', models.CharField(blank=True, default='', max_length=200, verbose_name='Drivstoff')),
                ('operator', models.CharField(blank=True, default='', max_length=200, verbose_name='Operatør')),
            ],
            options={
                'ordering': ['numlow'],
            },
        ),
        migrations.AddField(
            model_name='expected_vehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_type.vehicle'),
        ),
    ]
