# Generated by Django 2.1.4 on 2019-07-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expected_vehicle',
            new_name='ExpectedVehicle',
        ),
        migrations.AlterField(
            model_name='expectedvehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_type.Vehicle'),
        ),
    ]
