# Generated by Django 2.1.4 on 2019-07-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0009_auto_20190729_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='num_prefix',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ekstra sifer foran internnummer'),
        ),
        migrations.AlterField(
            model_name='expectedvehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_type.Vehicle'),
        ),
    ]
