# Generated by Django 3.1.5 on 2021-05-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0011_auto_20190824_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Drivstoff'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lengde'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle_type.operator', verbose_name='Operatør'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Type/modell'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Årsmodell'),
        ),
    ]
