# Generated by Django 2.1.4 on 2019-07-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndStops',
            fields=[
                ('service_journey_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_quay', models.CharField(max_length=200)),
                ('last_quay', models.CharField(max_length=200)),
                ('first_passing', models.TimeField()),
                ('last_passing', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('TransportMode', models.CharField(blank=True, max_length=200, null=True)),
                ('TransportSubmode', models.CharField(blank=True, max_length=200, null=True)),
                ('PublicCode', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linjenummer')),
                ('OperatorRef', models.CharField(blank=True, max_length=200, null=True, verbose_name='Operatør')),
                ('RepresentedByGroupRef', models.CharField(blank=True, max_length=200, null=True)),
                ('Colour', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='endstops',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='sanntid.Line'),
        ),
    ]
