# Generated by Django 2.1.4 on 2019-07-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanntid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endstops',
            name='line_id_string',
            field=models.CharField(db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endstops',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='sanntid.Line'),
        ),
    ]
